// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aagixqjtpkztlajzzyxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZ2l4cWp0cGt6dGxhanp6eXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzQ1NzUsImV4cCI6MjA2NTE1MDU3NX0.Ob5gBiouZs5jDiU2N3aj-w9zS7iqbTYeJ53TXYHkQr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);